version: '3.7'

services:
  vscode:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/dev/.ssh
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
      - cargo-cache:/home/dev/.cargo
    command: sleep infinity
    environment:
      XDG_RUNTIME_DIR: ${XDG_RUNTIME_DIR}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}

volumes:
  cargo-cache: